# Generated by Django 4.2.7 on 2023-12-02 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modaldata',
            name='columns12',
        ),
        migrations.RemoveField(
            model_name='modaldata',
            name='columns13',
        ),
        migrations.RemoveField(
            model_name='modaldata',
            name='columns14',
        ),
        migrations.RemoveField(
            model_name='modaldata',
            name='columns15',
        ),
        migrations.RemoveField(
            model_name='modaldata',
            name='columns16',
        ),
        migrations.RemoveField(
            model_name='modaldata',
            name='columns17',
        ),
    ]
